/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-configs-recommended.js' */
"use strict";

module.exports = {
    plugins: ["spiff"],
    rules: {
        "spiff/example-rule": "error"
    }
};
